#!/bin/sh
# -*- sh -*-

#
# Written by: Francesco Salvestrini <f DOT salvestrini AT nextworks DOT it>
#

#
# Script-local parameters
#

#
# Do not change under this line
#

ME=install-from-scratch

BUILDERDIR=builder

. ./$BUILDERDIR/.env || {
    echo "$ME: Cannot load environment"
    exit 1
}

./$BUILDERDIR/install-kernel-from-scratch $@ || {
    echo "$ME: Cannot compile or install the kernel from scratch"
    exit 1
}

./$BUILDERDIR/install-user-from-scratch $@ || {
    echo "$ME: Cannot install the user parts from scratch"
    exit 1
}
